bolt.lo: /Users/lunereaper/Projects/bolt/ext/bolt.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt.c -o bolt.lo 
kernel/main.lo: /Users/lunereaper/Projects/bolt/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /Users/lunereaper/Projects/bolt/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /Users/lunereaper/Projects/bolt/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /Users/lunereaper/Projects/bolt/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /Users/lunereaper/Projects/bolt/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /Users/lunereaper/Projects/bolt/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /Users/lunereaper/Projects/bolt/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /Users/lunereaper/Projects/bolt/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /Users/lunereaper/Projects/bolt/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /Users/lunereaper/Projects/bolt/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /Users/lunereaper/Projects/bolt/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /Users/lunereaper/Projects/bolt/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /Users/lunereaper/Projects/bolt/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /Users/lunereaper/Projects/bolt/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/operators.c -o kernel/operators.lo 
kernel/concat.lo: /Users/lunereaper/Projects/bolt/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /Users/lunereaper/Projects/bolt/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /Users/lunereaper/Projects/bolt/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /Users/lunereaper/Projects/bolt/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/exit.lo: /Users/lunereaper/Projects/bolt/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/kernel/exit.c -o kernel/exit.lo 
bolt/exception.lo: /Users/lunereaper/Projects/bolt/ext/bolt/exception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/exception.zep.c -o bolt/exception.lo 
bolt/app/exception.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/exception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/exception.zep.c -o bolt/app/exception.lo 
bolt/app/router.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/router.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/router.zep.c -o bolt/app/router.lo 
bolt/app/view.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/view.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/view.zep.c -o bolt/app/view.lo 
bolt/app/router/exception.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/router/exception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/router/exception.zep.c -o bolt/app/router/exception.lo 
bolt/app/router/route.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/router/route.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/router/route.zep.c -o bolt/app/router/route.lo 
bolt/app/view/compiler.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/view/compiler.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/view/compiler.zep.c -o bolt/app/view/compiler.lo 
bolt/app/view/context.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/view/context.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/view/context.zep.c -o bolt/app/view/context.lo 
bolt/app/view/exception.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/view/exception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/view/exception.zep.c -o bolt/app/view/exception.lo 
bolt/app/view/parser.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/view/parser.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/view/parser.zep.c -o bolt/app/view/parser.lo 
bolt/app/view/template.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/view/template.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/view/template.zep.c -o bolt/app/view/template.lo 
bolt/app/view/tokenizer.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/view/tokenizer.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/view/tokenizer.zep.c -o bolt/app/view/tokenizer.lo 
bolt/app/view/parser/node.lo: /Users/lunereaper/Projects/bolt/ext/bolt/app/view/parser/node.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/app/view/parser/node.zep.c -o bolt/app/view/parser/node.lo 
bolt/http/request.lo: /Users/lunereaper/Projects/bolt/ext/bolt/http/request.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/lunereaper/Projects/bolt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lunereaper/Projects/bolt/ext/bolt/http/request.zep.c -o bolt/http/request.lo 
$(phplibdir)/bolt.la: ./bolt.la
	$(LIBTOOL) --mode=install cp ./bolt.la $(phplibdir)

./bolt.la: $(shared_objects_bolt) $(BOLT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_bolt) $(BOLT_SHARED_LIBADD)

